// SPDX-FileCopyrightText: 2026 wagaStrim contributors
// SPDX-License-Identifier: MIT

// Package signal is the public listener. It is deliberately not the same
// listener as the settings UI: everything here is reachable from the internet
// and gated on a key, and nothing here may expose settings.
package signal

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strings"
	"time"

	"github.com/MarcFryd/wagaStrim/internal/config"
	"github.com/MarcFryd/wagaStrim/internal/ingest"
	"github.com/pion/logging"
)

const (
	shutdownGrace = 5 * time.Second
	maxOfferBytes = 256 << 10
)

// Server routes WHIP over HTTP to the ingest package.
type Server struct {
	cfg    *config.Config
	log    logging.LeveledLogger
	whip   *ingest.Server
	http   *http.Server
	listen string
}

// New wires the routes. The listener binds every interface, because a phone on
// cellular has to reach it.
func New(cfg *config.Config, log logging.LeveledLogger, whip *ingest.Server) *Server {
	srv := &Server{
		cfg:    cfg,
		log:    log,
		whip:   whip,
		listen: fmt.Sprintf(":%d", cfg.SignalPort),
	}

	mux := http.NewServeMux()
	mux.HandleFunc("POST /whip/{key}", srv.handlePublish)
	mux.HandleFunc("DELETE /whip/resource/{resource}", srv.handleTeardown)

	srv.http = &http.Server{
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	return srv
}

// Serve blocks until the context is canceled.
func (s *Server) Serve(ctx context.Context) error {
	var lcfg net.ListenConfig

	listener, err := lcfg.Listen(ctx, "tcp", s.listen)
	if err != nil {
		return fmt.Errorf("%w: signaling on %s: %w", ErrServe, s.listen, err)
	}

	errs := make(chan error, 1)

	go func() { errs <- s.http.Serve(listener) }()

	s.log.Infof("signaling on %s", listener.Addr())

	select {
	case err := <-errs:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}

		return fmt.Errorf("%w: %w", ErrServe, err)
	case <-ctx.Done():
		stop, cancel := context.WithTimeout(context.WithoutCancel(ctx), shutdownGrace)
		defer cancel()

		return s.http.Shutdown(stop)
	}
}

func (s *Server) handlePublish(wri http.ResponseWriter, req *http.Request) {
	offer, err := io.ReadAll(http.MaxBytesReader(wri, req.Body, maxOfferBytes))
	if err != nil {
		http.Error(wri, "offer too large", http.StatusRequestEntityTooLarge)

		return
	}

	answer, resource, err := s.whip.Publish(req.PathValue("key"), string(offer))
	if err != nil {
		s.reject(wri, req.PathValue("key"), err)

		return
	}

	wri.Header().Set("content-type", "application/sdp")
	// The answer is generated by our own PeerConnection, not echoed from the
	// request, but it is derived from a request the taint analyser can see. The
	// vector it is worried about is a browser sniffing application/sdp as HTML,
	// so refuse sniffing outright rather than reasoning about the provenance.
	wri.Header().Set("x-content-type-options", "nosniff")
	wri.Header().Set("location", "/whip/resource/"+resource)
	wri.WriteHeader(http.StatusCreated)

	// #nosec G705 -- SDP from our own PeerConnection, served nosniff as application/sdp.
	if _, err := wri.Write([]byte(answer)); err != nil {
		s.log.Warnf("write answer: %v", err)
	}
}

func (s *Server) handleTeardown(wri http.ResponseWriter, req *http.Request) {
	if err := s.whip.Teardown(req.PathValue("resource")); err != nil {
		http.Error(wri, "not found", http.StatusNotFound)

		return
	}

	wri.WriteHeader(http.StatusNoContent)
}

// reject turns a failure into the most useful thing that can be said without
// telling an unauthenticated caller anything. A caller holding a real key for
// this ingest already knows the ingest exists, so naming the mix-up leaks
// nothing; everyone else gets an undifferentiated 404.
func (s *Server) reject(wri http.ResponseWriter, key string, cause error) {
	s.log.Warnf("publish rejected: %v", cause)

	switch {
	case errors.Is(cause, ingest.ErrWrongRole):
		http.Error(wri,
			"This is the receiver link, which belongs in OBS. Moblin needs the sender link.",
			http.StatusBadRequest)
	case errors.Is(cause, ingest.ErrNotSending):
		http.Error(wri,
			"This endpoint publishes media. An OBS receiver should use the receiver link instead.",
			http.StatusBadRequest)
	case errors.Is(cause, ingest.ErrAlreadyLive):
		http.Error(wri, "That camera already has a publisher.", http.StatusConflict)
	case errors.Is(cause, ingest.ErrUnknownKey):
		http.Error(wri, "not found", http.StatusNotFound)
	default:
		s.logKeyShape(key)
		http.Error(wri, "cannot negotiate", http.StatusBadRequest)
	}
}

// logKeyShape records only whether the key looked like one of ours, never the key.
func (s *Server) logKeyShape(key string) {
	switch {
	case strings.HasPrefix(key, config.SenderPrefix):
		s.log.Warnf("failed negotiation for a sender key")
	case strings.HasPrefix(key, config.ReceiverPrefix):
		s.log.Warnf("failed negotiation for a receiver key")
	default:
		s.log.Warnf("failed negotiation for an unrecognized key shape")
	}
}
